# Generated by Django 4.2.17 on 2025-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
