# Generated by Django 4.2.17 on 2025-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviecard_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecard',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
