# Generated by Django 4.2.17 on 2025-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_movie_vote_movie_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
